[package]
name = "alef-compiler"
version = "0.0.1-alpha"
description = "The AOT Compiler of Alef Component."
repository = "https://github.com/alephjs/alef-component"
license = "MIT"
authors = ["The Alef Component authors"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
anyhow = "1.0.34"
base64 = "0.13.0"
indexmap = "1.6.0"
lazy_static = "1.4.0"
rand = { version = "0.7.3", features = ["wasm-bindgen"]}
regex = "1.4.2"
sha-1 = "0.9.2"
serde = { version = "1.0.118", features = ["derive"] }
cssparser = "0.28.0"

# swc
# docs: https://swc.rs
swc_common = { version = "0.10.7", features = ["sourcemap"] }
swc_ecmascript = { version = "0.14.5", features = ["codegen", "parser",  "transforms", "visit"] }
swc_ecma_ast = "0.35.0"
swc_ecma_visit = "0.21.0"
swc_ecma_utils = "0.25.0"

# wasm-bindgen
# docs: https://rustwasm.github.io/docs/wasm-bindgen
wasm-bindgen = {version = "0.2.69", features = ["serde-serialize"]}
console_error_panic_hook = { version = "0.1.6", optional = true }

[profile.release]
# Tell `rustc` to optimize for speed
lto = true
